import type { Metadata } from 'next';
import classNames from 'classnames';

import { ReactQueryProvider } from '@/providers';

import { pretendard } from './fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Pi Plus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={classNames('size-full flex-1', pretendard.className)}>
        <ReactQueryProvider>
          <div className="flex min-h-screen w-full">{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
