import type { Metadata } from 'next';

import { ReactQueryProvider } from '@/components/providers';

import './globals.css';

export const metadata: Metadata = {
  title: 'Pi Plus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="size-full flex-1">
        <ReactQueryProvider>
          <div className="flex min-h-screen w-full">{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
